Wingoo/urls.py
from django.contrib import admin
from django.urls import path, include
#change this lat to lines !!! 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashbord', include('dashbord.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Big problem Change it for porduction !!!!

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

from .forms import loginForm 



app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/',views.contact, name='contact'),
    path('signup/',views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=loginForm), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
]

dashbord/urls.py
from django.urls import path
from . import views

app_name= 'dashbord'

urlpatterns= [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'


urlpatterns = [
    path('', views.search, name='search'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/',views.new, name='new' ),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class loginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl max-auto'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl max-auto'
    }))



class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields= ('username','email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl max-auto'
    }))


    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your Email',
        'class': 'w-full py-4 px-6 rounded-xl max-auto'
    }))


    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your Password',
        'class': 'w-full py-4 px-6 rounded-xl max-auto'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'ReEnter Password',
        'class': 'w-full py-4 px-6 rounded-xl max-auto'
    }))

core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm
from django.contrib.auth import login
from item.models import Category, Item

# Create your views here.


def index(request):
    items = Item.objects.filter(is_sold = False).all()
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories' : categories,
        'items' : items,
    })

def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            user=form.save()
            login(request, user)

            next_url = request.GET.get('next', None)
            if next_url:
                return redirect(next_url)
            else:
                return redirect('core:index')  # Redirect to a default page if 'next' parameter is not present

    else: 
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %}</title>
    <style>
        .footer {

            border-radius: 12px;
            width: auto;
            margin-left: 2rem;
            margin-right: 2rem;
            background-color: #009933; /* Match the background color of the containers */
            padding: 20px;
            display: flex;
            justify-content: space-between;
            
        }

        .about-us, .categories {
            flex-basis: 30%; /* Adjusted width to match the containers */
        }

        .footer h3 {
            text-align: right;
            margin-bottom: 15px;
            font-weight: 900;
            color: #ffff;
            font-size: x-large;
            font-family: Sri-TSCRegular;
            src: url('sri-tsc-webfont.eot');
            src: url('sri-tsc-webfont.eot?#iefix') format('embedded-opentype'),
            url('sri-tsc-webfont.woff') format('woff'),
            url('sri-tsc-webfont.ttf') format('truetype'),
            url('sri-tsc-webfont.svg#Sri-TSCRegular') format('svg');
        }

        .footer p {
            text-align: right;
            width: 70%; /* Adjusted width to match the containers */
            font-size: 18px;
            line-height: 1.5;
            color: #dadada;
        }

        .footer ul {
            text-align: right;
            list-style: none;
            padding: 1%;
        }
    </style>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between item-center border-b border-green-700">
        <a href="/" class="text-xl font-bold">Wingoo</a>

        <div class="space-x-6">
            {% if request.user.is_authenticated %}
            <a href="{% url 'dashbord:index' %}" class="px-2 p-3 text-lg font-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">داشبورد</a>
            <form action="{% url 'core:logout' %}" method="post" class="inline">
                {% csrf_token %}
                <button type="submit" class="px-2 p-2.5 text-lg font-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">خروج‌ از‌ حساب</button>
            </form>
                {% else %}
                    <a href="{% url 'core:signup' %}?next={{ request.path|urlencode }}" class="px-2 py-3 text-lg font-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">عضویت</a>
                    <a href="{% url 'core:login' %}?next={{ request.path|urlencode }}" class="px-3 py-3 text-lg font-bold bg-green-500 text-white rounded-xl hover:bg-green-500">ورود</a>
            {% endif %}    
            <a href="{% url 'item:search' %}" class="text-lg font-bold p-3">گشتن</a>
            <a href="{% url 'item:new' %}" class="text-lg font-bold p-3 hover:text-green-500 ">آگهی جدید</a>
        </div>
    </nav>

    
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>


    <footer class="footer">
        <section class="about-us">
            <h3 style="text-align: left; padding-left: 50%;" dir="rtl">درباره ما :</h3>
            <p  dir='rtl'>وینگو، یک مارکت‌ پلیس  برای لوازم هوانوری خواهد بود .</p>
        </section>
        <section class="categories">
            <h3>دسته بندی‌ها</h3>
            <ul>
                {% for category in categories %}
                    <li>{{ category.name }}: {{ category.items.count }} عدد</li>
                {% endfor %}
            </ul>
        </section>
    </footer>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}


{% block title %}Contect{% endblock %}


{% block content %}
    <h1>contact page</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Wingoo{% endblock %}

{% block content %}
    <style>
        .container, .container2 {
            margin-top: 0.5rem;
            margin-bottom: 0.5rem;
            width: 100%;
            margin-left: auto;
            margin-right: auto;
            background-color: #e6e6e6;
            border-radius: 12px; /* Adjust the value to change the roundness of the corners */
            padding: 20px; /* Adjust the padding to control the content size within the container */
        }

        .title {
            text-align: center;
            font-size: xx-large;
            font-weight: 600;
            font-style: 'yekan';
            margin-bottom: 2.5rem;
        }

        .item img {
            border-radius: 14px;
            height: 60%;
            margin-left: auto;
            margin-right: auto;
        }

        .item-details {
            text-align: center;
            font-size: x-large;
            font-family: 'Yekan';
        }
    </style>

    <div class="container">
        <h2 class="title">جدیدترین محصولات</h2>

        
        <div class="grid grid-cols-5 gap-4 ">
            {% for item in items %}
                <div class="item">
                    <a href="{% url 'item:detail' item.id %}">
                        <img src="{{ item.item_profile.url }}" alt="{{ item.name }}">
                        <div class="item-details">
                            <h2>{{ item.name }}</h2>
                            <p>قیمت: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="container">
        <h2 class="title">دسته بندی‌ها</h2>
        <div class="grid grid-cols-{{categories.count}} gap-{{categories.count}}">
            {% for category in categories %}
                <div class="item">
                    <a href="#">
                        <ul class="item-details">
                            <li>{{ category.name }}: {{ category.items.count }}</li>
                        </ul>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-2xl p-6 ">
        <h1 class="mb-6 text-4xl text-center">Login</h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_username" class="inline-block mb-2 mx-left">Username</label><br>
                {{ form.username }}
            </div>
            <div class="mb-3">
                <label for="id_password1" class="inline-block mb-2 mx-left">Password</label><br>
                {{ form.password }}
            </div>
            {% if form.errors %}
            <div class="mb-3 p-6 bg-red-200 rounded-xl">
                {% for field in form %}
                    {% for error in field.errors %}
                        {{ error }}
                        {% endfor %}
                    {% endfor %}
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            <button type="submit" class="w-1/3 mt-4 mb-4 py-4 px-4 text-xl bg-teal-500 rounded-2xl text-white">ورود</button>
        </form>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Signup{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 mx-auto bg-gray-100 rounded-2xl p-6 ">
        <h1 class="mb-6 text-4xl text-center">Sign Up</h1>
        <form method="POST" action=".">
            {% csrf_token %}

            
            <div class="mb-3">
                <label class="inline-block mb-2 mx-left">username</label></br>
                {{ form.username}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 mx-left">Email</label></br>
                {{ form.email}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 mx-left">Password</label></br>
                {{ form.password1}}
            </div>
            <div class="mb-3">
                <label class="inline-block mb-2 mx-left">Repeat Password</label></br>
                {{ form.password2}}
            </div>
            {% if form.errosrs or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-200 rounded-xl">
                {% for field in form %}
                    {{ field.errosrs }}
                    {{ form.non_field_errors }}
                {% endfor %}
            </div>
            {% endif %}
            <button type="submit" class="w-1/3 mt-4 mb-4 py-4 px-4 text-xl bg-teal-500 rounded-2xl text-white">Submit</button>

        </form>
    </div>

{% endblock %}