Wingoo/urls.py
from django.contrib import admin
from django.urls import path, include
#change this lat to lines !!! 
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashbord', include('dashbord.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # Big problem Change it for porduction !!!!

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

from .forms import loginForm 



app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/',views.contact, name='contact'),
    path('signup/',views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=loginForm), name='login'),
    path('logout/',auth_views.LogoutView.as_view(), name='logout'),
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'


urlpatterns = [
    path('', views.search, name='search'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/',views.new, name='new' ),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit', views.edit, name='edit'),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User




# Create your models here.
                            # Ok 

class Category(models.Model):
    name = models.CharField(max_length=30)

    class Meta:
        ordering = ('name', )
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name 
    

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField(blank=False)
    item_profile = models.ImageField(upload_to='item_images', blank=False, null=False)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name 

item/forms.py
from django import forms
from .models import Item 

INPUT_CLASS = 'w-full py-4 px-6 rounded-xl border'
class newItemForm(forms.ModelForm):
    class Meta : 
        model = Item
        fields = ('category', 'name', 'price', 'description', 'item_profile')

        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASS
            }),

            'name': forms.TextInput(attrs={
                'class': INPUT_CLASS
            }),
    
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASS
            }),
            
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASS
            }),

            'item_profile': forms.FileInput(attrs={
                'class': INPUT_CLASS
            }),
        }

class EditItemForm(forms.ModelForm):
    class Meta : 
        model = Item
        fields = ('name', 'price', 'description', 'item_profile', 'is_sold')

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASS
            }),
    
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASS
            }),
            
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASS
            }),

            'item_profile': forms.FileInput(attrs={
                'class': INPUT_CLASS
            }),
        }

item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q 
from django.shortcuts import render, get_object_or_404, redirect

from .models import Item, Category
from .forms import newItemForm, EditItemForm

# Create your views here.

def search(request):
    query = request.GET.get('query', '')
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()
    category_id = request.GET.get('category', 0)
    
    if category_id:
        items = items.filter(category_id= category_id)

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    
    return render(request, 'item/browser.html', {
        'items': items,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })


def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[:3] 
    return render(request, 'item/detail.html', {
        'item': item,
        'related_items' : related_items,
    })


@login_required
def new(request): 
    if request.method == "POST":
        form = newItemForm(request.POST, request.FILES)
    
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            
            return redirect('item:detail', pk= item.id)
    else:
        form = newItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item'
    })


@login_required
def edit(request, pk): 
    item = get_object_or_404(Item, pk=pk, created_by = request.user)

    if request.method == "POST":
        form = EditItemForm(request.POST, request.FILES, instance=item)
    
        if form.is_valid():
            form.save()            
            return redirect('item:detail', pk= item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item'
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by = request.user)
    item.delete()
    return redirect('dashbord:index')

item/templates/item/browser.html
{% extends 'core/base.html' %}

{% block title %}Browse{% endblock %}

{% block content %}

    <div class="pb-6 grid grid-cols-5 gap-4 bg-gray-100 p-6">
        <div class="col-span-1">
            <form action="{% url 'item:search' %}" method="get">
                <input name="query" class="w-full py-4 px-6 border rounded-xl " type="search" value="{{ query }}" dir="rtl" placeholder="جست و جو کنید">

                <button class="mt-2 py-4 px-8 text-lg bg-green-500 rounded-xl text-white">گشتن</button>

                <hr class="my-6">
                <p class="text-center text-lg">دسته بندی‌ها</p>
                <ul>
                    {% for category in categories %}
                        <li class="py-2 px-2 rounded-xl {% if category.id == category_id %} bg-green-100{% endif %}">
                            <a href="{% url 'item:search' %}?query={{ query }}&category={{ category.id }} ">{{ category.name }} : {{ category.items.count }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <hr class="my-6">
                <p class="text-center text-lg">حذف فیلتر ها</p>
                <div class="text-center p-4 bg-red-300 mt-2 py-4 px-8 text-xl text-white rounded-xl">
                    <a href="{% url 'item:search' %}" class="text-center">حذف</a>
                </div>

            </form>
        </div>
        <div class="col-span-4">

            <div class="grid grid-cols-4 gap-4">
                {% for item in items %}
                    <div class="item">
                        <a href="{% url 'item:detail' item.id %}">
                            <div class="">
                                <img src="{{ item.item_profile.url }}" alt="{{ item.name }}" class=" object-cover h-48 w-96  rounded-t-xl">
                            </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-center text-xl ">{{ item.name }}</h2>
                                <p class=" text-center text-green-500">قیمت: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}


{% block title %}{{item.name}}{% endblock %}

{% block content %}

<div class="grid grid-cols-5 gap-6">

    <div class="col-span-3 ">
        <img src="{{ item.item_profile.url }}" alt="{{item.name}}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 dir="rtl" class="mb-6 text-3xl ">{{ item.name }}</h1>
        <p dir="rtl"class="text-gray-600 text-2xl"><strong>قیمت: </strong> {{ item.price }}</p>
        <p dir="rtl" class="text-gray-600 text-2xl py-4"><strong>فروشنده: </strong> {{ item.created_by.username }}</p>


        {% if item.description %}
            <p align="right"  dir="rtl" class="text-gray-800">
                <strong dir="rtl" class="text-gray-600">توضیحات:</strong></br>
                {{ item.description }}
            </p>
        {% endif %}
        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>این محصول شماست</p>
                <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl shadow-md ">ویرایش</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl shadow-md ">حذف آگهی</a>
            </div>
        {% else %}    
            <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-bold text-white bg-teal-600 rounded-xl hover:bg-teal-800 shadow-md  ">اطلاعات تماس</a>
        {% endif %}
    </div>
</div>
{% if related_items.count != 0 %}
    <div align="center"class="content-center">
        <h2 class="text-xl text-center p-6">محصولات‌ مرتبط</h2>
        <div class="grid grid-cols-4 gap-3 w-full ">
            {% for item in related_items %}
                <div class="item">
                    <a href="{% url 'item:detail' item.id %}">
                        <img src="{{ item.item_profile.url }}" alt="{{ item.name }}" class="rounded-t-xl ">
                        <div class="bg-gray-200 rounded-b-xl">
                            <h2 class="text-2xl text-center">{{ item.name }}</h2>
                            <p class="text-lg text-center">قیمت: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

{% endblock %}

item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl">{{title}}</h1>

    <form method="POST" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="sapce-y-4">
            {{ form.as_p}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-200 rounded-xl">
                {% for field in form %}
                    {% for error in field.errors %}
                        {{ error }}
                    {% endfor %}
                {% endfor %}
                {{ form.non_field_errors }}
            </div>
        {% endif %}
    
        <button type="submit" class="mt-6 w-1/3 mt-4 mb-4 py-4 px-4 text-xl bg-teal-500 rounded-2xl text-white">تایید</button>
    </form>
{% endblock %}